<?php
/**
 * AllRequestTypesExample
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Betfair: Exchange Streaming API
 *
 * API to receive streamed updates. This is an ssl socket connection of CRLF delimited json messages (see RequestMessage & ResponseMessage)
 *
 * OpenAPI spec version: 1.0.1423
 * Contact: bdp@betfair.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;

/**
 * AllRequestTypesExample Class Doc Comment
 *
 * @category    Class */
/** 
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AllRequestTypesExample implements ArrayAccess
{
    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'AllRequestTypesExample';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = array(
        'op_types' => 'string',
        'heartbeat' => '\Swagger\Client\Model\HeartbeatMessage',
        'order_subscription_message' => '\Swagger\Client\Model\OrderSubscriptionMessage',
        'market_subscription' => '\Swagger\Client\Model\MarketSubscriptionMessage',
        'authentication' => '\Swagger\Client\Model\AuthenticationMessage'
    );

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = array(
        'op_types' => 'opTypes',
        'heartbeat' => 'heartbeat',
        'order_subscription_message' => 'orderSubscriptionMessage',
        'market_subscription' => 'marketSubscription',
        'authentication' => 'authentication'
    );

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = array(
        'op_types' => 'setOpTypes',
        'heartbeat' => 'setHeartbeat',
        'order_subscription_message' => 'setOrderSubscriptionMessage',
        'market_subscription' => 'setMarketSubscription',
        'authentication' => 'setAuthentication'
    );

    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = array(
        'op_types' => 'getOpTypes',
        'heartbeat' => 'getHeartbeat',
        'order_subscription_message' => 'getOrderSubscriptionMessage',
        'market_subscription' => 'getMarketSubscription',
        'authentication' => 'getAuthentication'
    );

    public static function getters()
    {
        return self::$getters;
    }

    const OP_TYPES_HEARTBEAT = 'heartbeat';
    const OP_TYPES_AUTHENTICATION = 'authentication';
    const OP_TYPES_MARKET_SUBSCRIPTION = 'marketSubscription';
    const OP_TYPES_ORDER_SUBSCRIPTION = 'orderSubscription';
    

    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public function getOpTypesAllowableValues()
    {
        return [
            self::OP_TYPES_HEARTBEAT,
            self::OP_TYPES_AUTHENTICATION,
            self::OP_TYPES_MARKET_SUBSCRIPTION,
            self::OP_TYPES_ORDER_SUBSCRIPTION,
        ];
    }
    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = array();

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['op_types'] = isset($data['op_types']) ? $data['op_types'] : null;
        $this->container['heartbeat'] = isset($data['heartbeat']) ? $data['heartbeat'] : null;
        $this->container['order_subscription_message'] = isset($data['order_subscription_message']) ? $data['order_subscription_message'] : null;
        $this->container['market_subscription'] = isset($data['market_subscription']) ? $data['market_subscription'] : null;
        $this->container['authentication'] = isset($data['authentication']) ? $data['authentication'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = array();
        $allowed_values = array("heartbeat", "authentication", "marketSubscription", "orderSubscription");
        if (!in_array($this->container['op_types'], $allowed_values)) {
            $invalid_properties[] = "invalid value for 'op_types', must be one of #{allowed_values}.";
        }

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properteis are valid
     */
    public function valid()
    {
        $allowed_values = array("heartbeat", "authentication", "marketSubscription", "orderSubscription");
        if (!in_array($this->container['op_types'], $allowed_values)) {
            return false;
        }
        return true;
    }


    /**
     * Gets op_types
     * @return string
     */
    public function getOpTypes()
    {
        return $this->container['op_types'];
    }

    /**
     * Sets op_types
     * @param string $op_types
     * @return $this
     */
    public function setOpTypes($op_types)
    {
        $allowed_values = array('heartbeat', 'authentication', 'marketSubscription', 'orderSubscription');
        if (!in_array($op_types, $allowed_values)) {
            throw new \InvalidArgumentException("Invalid value for 'op_types', must be one of 'heartbeat', 'authentication', 'marketSubscription', 'orderSubscription'");
        }
        $this->container['op_types'] = $op_types;

        return $this;
    }

    /**
     * Gets heartbeat
     * @return \Swagger\Client\Model\HeartbeatMessage
     */
    public function getHeartbeat()
    {
        return $this->container['heartbeat'];
    }

    /**
     * Sets heartbeat
     * @param \Swagger\Client\Model\HeartbeatMessage $heartbeat
     * @return $this
     */
    public function setHeartbeat($heartbeat)
    {
        $this->container['heartbeat'] = $heartbeat;

        return $this;
    }

    /**
     * Gets order_subscription_message
     * @return \Swagger\Client\Model\OrderSubscriptionMessage
     */
    public function getOrderSubscriptionMessage()
    {
        return $this->container['order_subscription_message'];
    }

    /**
     * Sets order_subscription_message
     * @param \Swagger\Client\Model\OrderSubscriptionMessage $order_subscription_message
     * @return $this
     */
    public function setOrderSubscriptionMessage($order_subscription_message)
    {
        $this->container['order_subscription_message'] = $order_subscription_message;

        return $this;
    }

    /**
     * Gets market_subscription
     * @return \Swagger\Client\Model\MarketSubscriptionMessage
     */
    public function getMarketSubscription()
    {
        return $this->container['market_subscription'];
    }

    /**
     * Sets market_subscription
     * @param \Swagger\Client\Model\MarketSubscriptionMessage $market_subscription
     * @return $this
     */
    public function setMarketSubscription($market_subscription)
    {
        $this->container['market_subscription'] = $market_subscription;

        return $this;
    }

    /**
     * Gets authentication
     * @return \Swagger\Client\Model\AuthenticationMessage
     */
    public function getAuthentication()
    {
        return $this->container['authentication'];
    }

    /**
     * Sets authentication
     * @param \Swagger\Client\Model\AuthenticationMessage $authentication
     * @return $this
     */
    public function setAuthentication($authentication)
    {
        $this->container['authentication'] = $authentication;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


