<?php
/**
 * MarketDataFilter
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Betfair: Exchange Streaming API
 *
 * API to receive streamed updates. This is an ssl socket connection of CRLF delimited json messages (see RequestMessage & ResponseMessage)
 *
 * OpenAPI spec version: 1.0.1423
 * Contact: bdp@betfair.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;

/**
 * MarketDataFilter Class Doc Comment
 *
 * @category    Class */
/** 
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MarketDataFilter implements ArrayAccess
{
    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'MarketDataFilter';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = array(
        'ladder_levels' => 'int',
        'fields' => 'string[]'
    );

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = array(
        'ladder_levels' => 'ladderLevels',
        'fields' => 'fields'
    );

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = array(
        'ladder_levels' => 'setLadderLevels',
        'fields' => 'setFields'
    );

    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = array(
        'ladder_levels' => 'getLadderLevels',
        'fields' => 'getFields'
    );

    public static function getters()
    {
        return self::$getters;
    }

    const FIELDS_EX_BEST_OFFERS_DISP = 'EX_BEST_OFFERS_DISP';
    const FIELDS_EX_BEST_OFFERS = 'EX_BEST_OFFERS';
    const FIELDS_EX_ALL_OFFERS = 'EX_ALL_OFFERS';
    const FIELDS_EX_TRADED = 'EX_TRADED';
    const FIELDS_EX_TRADED_VOL = 'EX_TRADED_VOL';
    const FIELDS_EX_LTP = 'EX_LTP';
    const FIELDS_EX_MARKET_DEF = 'EX_MARKET_DEF';
    const FIELDS_SP_TRADED = 'SP_TRADED';
    const FIELDS_SP_PROJECTED = 'SP_PROJECTED';
    

    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public function getFieldsAllowableValues()
    {
        return [
            self::FIELDS_EX_BEST_OFFERS_DISP,
            self::FIELDS_EX_BEST_OFFERS,
            self::FIELDS_EX_ALL_OFFERS,
            self::FIELDS_EX_TRADED,
            self::FIELDS_EX_TRADED_VOL,
            self::FIELDS_EX_LTP,
            self::FIELDS_EX_MARKET_DEF,
            self::FIELDS_SP_TRADED,
            self::FIELDS_SP_PROJECTED,
        ];
    }
    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = array();

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['ladder_levels'] = isset($data['ladder_levels']) ? $data['ladder_levels'] : null;
        $this->container['fields'] = isset($data['fields']) ? $data['fields'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = array();
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properteis are valid
     */
    public function valid()
    {
        return true;
    }


    /**
     * Gets ladder_levels
     * @return int
     */
    public function getLadderLevels()
    {
        return $this->container['ladder_levels'];
    }

    /**
     * Sets ladder_levels
     * @param int $ladder_levels
     * @return $this
     */
    public function setLadderLevels($ladder_levels)
    {
        $this->container['ladder_levels'] = $ladder_levels;

        return $this;
    }

    /**
     * Gets fields
     * @return string[]
     */
    public function getFields()
    {
        return $this->container['fields'];
    }

    /**
     * Sets fields
     * @param string[] $fields
     * @return $this
     */
    public function setFields($fields)
    {
        $allowed_values = array('EX_BEST_OFFERS_DISP', 'EX_BEST_OFFERS', 'EX_ALL_OFFERS', 'EX_TRADED', 'EX_TRADED_VOL', 'EX_LTP', 'EX_MARKET_DEF', 'SP_TRADED', 'SP_PROJECTED');
        if (!in_array($fields, $allowed_values)) {
            throw new \InvalidArgumentException("Invalid value for 'fields', must be one of 'EX_BEST_OFFERS_DISP', 'EX_BEST_OFFERS', 'EX_ALL_OFFERS', 'EX_TRADED', 'EX_TRADED_VOL', 'EX_LTP', 'EX_MARKET_DEF', 'SP_TRADED', 'SP_PROJECTED'");
        }
        $this->container['fields'] = $fields;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


