<?php
/**
 * MarketFilterTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Betfair: Exchange Streaming API
 *
 * API to receive streamed updates. This is an ssl socket connection of CRLF delimited json messages (see RequestMessage & ResponseMessage)
 *
 * OpenAPI spec version: 1.0.1423
 * Contact: bdp@betfair.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * MarketFilterTest Class Doc Comment
 *
 * @category    Class */
// * @description MarketFilter
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MarketFilterTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "MarketFilter"
     */
    public function testMarketFilter()
    {

    }

    /**
     * Test attribute "country_codes"
     */
    public function testPropertyCountryCodes()
    {

    }

    /**
     * Test attribute "betting_types"
     */
    public function testPropertyBettingTypes()
    {

    }

    /**
     * Test attribute "turn_in_play_enabled"
     */
    public function testPropertyTurnInPlayEnabled()
    {

    }

    /**
     * Test attribute "market_types"
     */
    public function testPropertyMarketTypes()
    {

    }

    /**
     * Test attribute "venues"
     */
    public function testPropertyVenues()
    {

    }

    /**
     * Test attribute "market_ids"
     */
    public function testPropertyMarketIds()
    {

    }

    /**
     * Test attribute "event_type_ids"
     */
    public function testPropertyEventTypeIds()
    {

    }

    /**
     * Test attribute "event_ids"
     */
    public function testPropertyEventIds()
    {

    }

    /**
     * Test attribute "bsp_market"
     */
    public function testPropertyBspMarket()
    {

    }

}
