<?php
/**
 * MarketDefinitionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Betfair: Exchange Streaming API
 *
 * API to receive streamed updates. This is an ssl socket connection of CRLF delimited json messages (see RequestMessage & ResponseMessage)
 *
 * OpenAPI spec version: 1.0.1423
 * Contact: bdp@betfair.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * MarketDefinitionTest Class Doc Comment
 *
 * @category    Class */
// * @description MarketDefinition
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class MarketDefinitionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "MarketDefinition"
     */
    public function testMarketDefinition()
    {

    }

    /**
     * Test attribute "venue"
     */
    public function testPropertyVenue()
    {

    }

    /**
     * Test attribute "settled_time"
     */
    public function testPropertySettledTime()
    {

    }

    /**
     * Test attribute "timezone"
     */
    public function testPropertyTimezone()
    {

    }

    /**
     * Test attribute "each_way_divisor"
     */
    public function testPropertyEachWayDivisor()
    {

    }

    /**
     * Test attribute "regulators"
     */
    public function testPropertyRegulators()
    {

    }

    /**
     * Test attribute "market_type"
     */
    public function testPropertyMarketType()
    {

    }

    /**
     * Test attribute "market_base_rate"
     */
    public function testPropertyMarketBaseRate()
    {

    }

    /**
     * Test attribute "number_of_winners"
     */
    public function testPropertyNumberOfWinners()
    {

    }

    /**
     * Test attribute "country_code"
     */
    public function testPropertyCountryCode()
    {

    }

    /**
     * Test attribute "in_play"
     */
    public function testPropertyInPlay()
    {

    }

    /**
     * Test attribute "bet_delay"
     */
    public function testPropertyBetDelay()
    {

    }

    /**
     * Test attribute "bsp_market"
     */
    public function testPropertyBspMarket()
    {

    }

    /**
     * Test attribute "betting_type"
     */
    public function testPropertyBettingType()
    {

    }

    /**
     * Test attribute "number_of_active_runners"
     */
    public function testPropertyNumberOfActiveRunners()
    {

    }

    /**
     * Test attribute "event_id"
     */
    public function testPropertyEventId()
    {

    }

    /**
     * Test attribute "cross_matching"
     */
    public function testPropertyCrossMatching()
    {

    }

    /**
     * Test attribute "runners_voidable"
     */
    public function testPropertyRunnersVoidable()
    {

    }

    /**
     * Test attribute "turn_in_play_enabled"
     */
    public function testPropertyTurnInPlayEnabled()
    {

    }

    /**
     * Test attribute "suspend_time"
     */
    public function testPropertySuspendTime()
    {

    }

    /**
     * Test attribute "discount_allowed"
     */
    public function testPropertyDiscountAllowed()
    {

    }

    /**
     * Test attribute "persistence_enabled"
     */
    public function testPropertyPersistenceEnabled()
    {

    }

    /**
     * Test attribute "runners"
     */
    public function testPropertyRunners()
    {

    }

    /**
     * Test attribute "version"
     */
    public function testPropertyVersion()
    {

    }

    /**
     * Test attribute "event_type_id"
     */
    public function testPropertyEventTypeId()
    {

    }

    /**
     * Test attribute "complete"
     */
    public function testPropertyComplete()
    {

    }

    /**
     * Test attribute "open_date"
     */
    public function testPropertyOpenDate()
    {

    }

    /**
     * Test attribute "market_time"
     */
    public function testPropertyMarketTime()
    {

    }

    /**
     * Test attribute "bsp_reconciled"
     */
    public function testPropertyBspReconciled()
    {

    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {

    }

}
